apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: example-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
    replicas: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral